Develop
interpriz/kenguru pull request #2
Opened 2022-09-20 11:13 UTC by interpriz

Андрей проверь пожалуйста пример организации сервиса на примере классов:

2022-09-20 13:30 UTC, turlarion requested changes
сделай хорошо плохо не делай

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
>      private WordsRepository wordsRepository;
Репозиторий в контроллере - плохо. Создавай сервис, там реализуй всю бизнес логику и туды выноси использование репозитория. А из контроллера вызывай сервис.

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
>      private UsersComparativeAdjectivesScoresRepository usersComparativeAdjectivesScoresRepository;
Репозиторий в контроллере - плохо. Создавай сервис, там реализуй всю бизнес логику и туды выноси использование репозитория. А из контроллера вызывай сервис.

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
> +    private ComparativeAdjectivesRepository comparativeAdjectivesRepository;
Репозиторий в контроллере - плохо. Создавай сервис, там реализуй всю бизнес логику и туды выноси использование репозитория. А из контроллера вызывай сервис.

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
>      private UsersPhrasalVerbsScoresRepository usersPhrasalVerbsScoresRepository;
Репозиторий в контроллере - плохо. Создавай сервис, там реализуй всю бизнес логику и туды выноси использование репозитория. А из контроллера вызывай сервис.

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
> +        Iterable<WordsPartOfSpeech> wps = wordsPartsOfSpeechRepository.findAll();
Зачем ты берешь Iterable, если у тебя метод возращает List? Лучше используй List, потому что он наследник Iterable и у него больше функций

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
> +        Iterable<UsersWords> uw = usersWordsRepository.findByUser(new Users(1L,"u"));
Та же ситуация с iterable и List

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
>          Iterable<UsersIrregularVerbsScores> uivs = usersIrregularVerbsScoresRepository.findByUser(new Users(1L,"u"));
Та же ситуация с iterable и List

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
>          Words word;
Вместо words.size()==0 используй words.isEmpty(). 
 Второе - почему у тебя возвращает список? если у тебя гарантированно в таблице одна запись, почему не вызвать метод findWordByName чтобы искать одну сущность, а не список?

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
>          if(wpsList.size()==0)
Вместо wpsList.size()==0 используй wpsList.isEmpty().
Второе - почему у тебя возвращает список? если у тебя гарантированно в таблице одна запись, почему не вызвать метод findWordPartOfSpeechByPartOfSpeechAndWord чтобы искать одну сущность, а не список?

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
>          if(uwList.size()==0)
Вместо uwList.size()==0 используй uwList.isEmpty().
Второе - почему у тебя возвращает список? если у тебя гарантированно в таблице одна запись, почему не вызвать метод findUsersWordByUserAndWps чтобы искать одну сущность, а не список?

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
>              if(translationsList.size()==0)
translationsList.isEmpty()
Поиск не списка а единственной сущности

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
> +        if(!newTranslation.equals(""))
тут лучше проверять при помощи метода String.isBlank()

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
> +        if(newTopic!="")
Нельзя сравнивать строки через == или !=. Почитай про String Pool в джаве, очень классная тема. а тут используй метод isBlank()

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
>              if(topicList.size()==0)
topicList.isEmpty()
Сущность вместо списка

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersWordsService.java
> +    private IrregularVerbsRepository irregular_verbsRepository;
Snake case

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersWordsService.java
> +        if(words.size()==0)
words.size() -> words.isEmpty()

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersWordsService.java
> +        if(wpsList.size()==0)
isEmpty

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersWordsService.java
> +        if(uwList.size()==0)
isEmpty

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersWordsService.java
> +        if(!newTranslation.equals(""))
isBlank()

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersWordsService.java
> +            if(translationsList.size()==0)
isEmpty()

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersWordsService.java
> +            Set<WordsTranslations> uwTranslations = usersWord.getTranslations();
Работа со ссылками и вынос логики в методы

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersWordsService.java
> +        if(!newTopic.equals(""))
isBlack()

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersWordsService.java
> +            Set<Topics> uwtTopics = usersWord.getTopics();
Работа со ссылками и вынос логики в методы

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersWordsService.java
> +            if(topicList.size()==0)
isEmpty()

2022-09-20 13:30 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersWordsService.java
> +            String topicName) {
Придумай DTO

2022-11-04 13:26 UTC, turlarion requested changes

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/config/WebSecurityConfig.java
> +                ;
зачем на новую строку?)

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
>          model.addAttribute("title", "История");
константный строки лучше выносить в отдельный класс в статические переменные

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
> +        model.addAttribute("usersWords", usersWords);
то же самое про константные строки

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
>          return "history";
константные строки

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
>          model.addAttribute("title", "Добавление форм неправильного глагола");
константные строки

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
>          return "addNewIrregularVerb";
константные строки

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
>          return "addNewComparativeAdjective";
константные строки

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/RegistrationController.java
> +        return "registration";
константные строки

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/RegistrationController.java
> +            return "registration";
константные строки

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/RestController.java
>      @GetMapping("/hellow")
очепятка

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/RestController.java
>      @GetMapping(value = "/findTranscriptionByWord")
вот тут прям по руками бить надо - почитай url naming convention

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/RestController.java
>      @GetMapping("/findWords")
url naming

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/UsersPhrasalVerbsController.java
> +    @GetMapping("/addNewPhrasalVerb")
url naming

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/UsersPhrasalVerbsController.java
> +        return "addNewPhrasalVerb";
константные строки

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/UsersPhrasalVerbsController.java
> +    @PostMapping("/addNewPhrasalVerb")
url naming

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/UsersPhrasalVerbsController.java
> +    @GetMapping("/editPhrasalVerb")
url naming

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/UsersWordsController.java
> +    @GetMapping("/addNewWord")
url naming

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/UsersWordsController.java
> +        List<PartsOfSpeech> ps = service.getAllPartsOfSpeech();
двухбуквенный нейминг не надо, уже обсуждали

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/UsersWordsController.java
> +    @PostMapping("/editWord")
url naming

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/dto/SearchingObjects.java
> +    private List<UsersWord> searchUserWords;
в нейминге переменных лучше не использовать глаголы
глаголы лучше использовать в именах методов
почитай про нейминг в гугле

https://www.comp.nus.edu.sg/~cs2103/AY1617S1/contents/coding-standards-java.html

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/dto/SearchingObjects.java
> +public class SearchingObjects {
что это вообще за класс и зачем он тут нужен?

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/dto/UsersPhrasalVerb.java
> +public class UsersPhrasalVerb {
почитай про фреймворк Lombok
его автогенерация кода может сильно сократить размер класса

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/dto/UsersPhrasalVerb.java
> +        this.word = UsersPhrasalVerb.getPhrasalVerb().getWps().getWord().getName();
не надо записывать в одну строку вызов нескольких методов подряд, максимум - два метода на строку, в идеале - один метод на одной строке

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/dto/UsersPhrasalVerb.java
> +        this.transcription = UsersPhrasalVerb.getPhrasalVerb().getWps().getWord().getTranscription();
инлайн чейнинга методов

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/dto/UsersPhrasalVerb.java
> +        for(PhrasalVerbsTranslations trans : UsersPhrasalVerb.getTranslations()){
я тебе рассказывать про механизм стримов в джаве. перечитай и можно сделать сильно короче и красивее

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/dto/UsersPhrasalVerb.java
> +    private String Description;
имя переменной с маленькой буквы, а не  с большой

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/dto/UsersWord.java
>          this.word = usersWord.getWps().getWord().getName();
тут и дальше в методе - инлайнинг чейнинга меотдов

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/dto/UsersWord.java
>          for(Topics top : usersWord.getTopics()){
стрим

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/entities/Users.java
>      private Long id;
лучше использовать UUID вместо лонга для ид, это надо будет править на уровне базы уже

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/entities/Users.java
>      private Set<UsersWords> uw;
опять сокращаешь слова до одной буквы

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/entities/Users.java
>      private Set<UsersComparativeAdjectivesScores> ucas;
опять сокращаешь слова до одной буквы

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/repositories/PhrasalVerbsRepository.java
> +    PhrasalVerbs findByWpsAndPreposition(WordsPartOfSpeech wps, String preposition);
я тебе рассказывать про тип данных Optional -  используй его чтобы избежать NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/repositories/IrregularVerbsRepository.java
> +    IrregularVerbs findByWps(WordsPartOfSpeech wps);
я тебе рассказывать про тип данных Optional - используй его чтобы избежать NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/repositories/ComparativeAdjectivesRepository.java
> +    ComparativeAdjectives findByWps(WordsPartOfSpeech wps);
я тебе рассказывать про тип данных Optional - используй его чтобы избежать NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/repositories/PhrasalVerbsTranslationsRepository.java
> +    PhrasalVerbsTranslations findByName(String name);
я тебе рассказывать про тип данных Optional - используй его чтобы избежать NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/repositories/TopicsRepository.java
> +    Topics findByName(String name);
я тебе рассказывать про тип данных Optional - используй его чтобы избежать NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/repositories/UsersComparativeAdjectivesScoresRepository.java
> +    UsersComparativeAdjectivesScores findByUserAndComparativeAdjective(Users usr, ComparativeAdjectives comparativeAdjective);
для сложных запросов лучше использовать аннотацию @Query()

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/repositories/UsersIrregularVerbsScoresRepository.java
> +    UsersIrregularVerbsScores findByUserAndIrregularVerb(Users usr, IrregularVerbs irregularVerb);
я тебе рассказывать про тип данных Optional - используй его чтобы избежать NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/repositories/UsersPhrasalVerbsScoresRepository.java
> +    UsersPhrasalVerbsScores findByUserAndPhrasalVerb(Users usr, PhrasalVerbs pv);
я тебе рассказывать про тип данных Optional - используй его чтобы избежать NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/repositories/UsersPhrasalVerbsScoresRepository.java
> +    UsersPhrasalVerbsScores findUsersPhrasalVerbsScoresById(Long id);
я тебе рассказывать про тип данных Optional - используй его чтобы избежать NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/repositories/UsersRepository.java
> +    Users findByUsername(String name);
я тебе рассказывать про тип данных Optional - используй его чтобы избежать NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/SearchingService.java
> +    public SearchingService(WordsPartOfSpeechRepository wordsPartsOfSpeechRepository,
очень много репозиториев - лучше разбить на подсервисы

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/SearchingService.java
> +            //если введен фразовый глагол с предлогом
откуда ты знаешь что тут фразовый глагол с предлогом, может просто какую-то белиберду написали?

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/SearchingService.java
> +            }
где третий else на случай если это не русский и не английский? это внештатная ситуация и её надо обработать а не бросать на произвол судьбы

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/SearchingService.java
> +        for (UsersWords userWord : searchUsersWords) {
стрим

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/SearchingService.java
> +        SearchingObjects result = new SearchingObjects(searchUsersWordsDTO, searchUsersPhrasalVerbsDTO);
вот этот класс это уже оверинжиниринг - думай как от него избавится

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UserService.java
> +        }else{
тут можешь избавиться от ветки else

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersCompAdjectivesService.java
> +        Words word = usersWordsService.saveOrGetWord(wordName, transcription);
откуда знаешь что wordName и transcription не null? потенциальное NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersCompAdjectivesService.java
> +        WordsPartOfSpeech wps = usersWordsService.saveOrGetWPS(pos, word);
NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersCompAdjectivesService.java
> +        UsersWords uw = usersWordsService.saveOrGetUsersWord(wps, user);
NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersIrregularVerbService.java
> +        String partOfSpeech = "verb";
константная строка

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersIrregularVerbService.java
> +        PartsOfSpeech pos = partsOfSpeechRepository.findPartsOfSpeechByName(partOfSpeech);
NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersIrregularVerbService.java
> +        Words word = usersWordsService.saveOrGetWord(wordName, transcription);
NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersIrregularVerbService.java
> +        WordsPartOfSpeech wps = usersWordsService.saveOrGetWPS(pos, word);
NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersIrregularVerbService.java
> +        UsersWords uw = usersWordsService.saveOrGetUsersWord(wps, user);
NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersIrregularVerbService.java
> +        IrregularVerbs irregularVerb = irregularVerbsRepository.findByWps(wps);
NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersPhrasalVerbsService.java
> +        String partOfSpeech = "verb";
константная строка

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersPhrasalVerbsService.java
> +        PartsOfSpeech pos = partsOfSpeechRepository.findPartsOfSpeechByName(partOfSpeech);
NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersPhrasalVerbsService.java
> +        Words word = usersWordsService.saveOrGetWord(wordName, transcription);
NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersPhrasalVerbsService.java
> +        WordsPartOfSpeech wps = usersWordsService.saveOrGetWPS(pos, word);
NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersPhrasalVerbsService.java
> +        UsersWords uw = usersWordsService.saveOrGetUsersWord(wps, user);
NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersPhrasalVerbsService.java
> +        if(!oldUsersPhrasalVerb.getPhrasalVerb().getPreposition().equals(preposition)){
инлайн чейнинга методов

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersWordsService.java
> +        WordsPartOfSpeech wps = saveOrGetWPS(pos, word);
NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersWordsService.java
> +        UsersWords usersWord = saveOrGetUsersWord(wps, user);
NPE

2022-11-04 13:26 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/services/UsersWordsService.java
> +        boolean newWordName = !oldUsersWord.getWps().getWord().getName().equals(wordName);
инлайнг чейнинга методов

2023-04-05 14:40 UTC, turlarion reviewed
делай хорошо плохо не делай

2023-04-05 14:40 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
> +        model.addAttribute("title", TITLE_MAIN_PAGE);
Тут вопрос чисто по неймингу - лучше тайтл писать в конце, к примеру MAIN_PAGE_TITLE

2023-04-05 14:40 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/RegistrationController.java
> +        return "registration";
константные строки

2023-04-05 14:40 UTC, turlarion commented on src/main/java/com/kenguru/demowebapp/controllers/RestController.java
> +        return searchingService.findWords_(usr,word);
зачем подчеркивание в имени метода? у нас не сейк-кейс

2023-06-29 07:03 UTC, interpriz commented on src/main/java/com/kenguru/demowebapp/controllers/MainController.java
> +        model.addAttribute("title", TITLE_MAIN_PAGE);
а что делать с ATTRIBUTE_USERS_WORDS тоже менять на USERS_WORDS_ATTRIBUTE?

2023-06-29 07:04 UTC, interpriz commented on src/main/java/com/kenguru/demowebapp/controllers/RegistrationController.java
> +        return "registration";
что делать с урлами по типу такого: "/activate/{code}" с параметрами? типо как их в нейминге учитывать?

2023-06-29 09:52 UTC, interpriz commented on src/main/java/com/kenguru/demowebapp/controllers/RestController.java
> +        return searchingService.findWords_(usr,word);
изменил на V2

2023-07-10 17:46 UTC, turlarion approved these changes
LGTM

2023-07-10 17:51 UTC, turlarion approved these changes

2023-07-10 17:57 UTC, merged